language: python
python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python test/test_parse.py